services:
  api:
    container_name: webgis-api
    build: .
    ports:
      - "4430:4430"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev # use npm start for production


